export const DEFAULT_ONBOARDING_TRIAL_DAYS = 30;
export const DEFAULT_ONBOARDING_TRIAL_DAYS_LABEL = `${DEFAULT_ONBOARDING_TRIAL_DAYS} days`;
export const DEFAULT_ONBOARDING_TRIAL_WINDOW_LABEL = `${DEFAULT_ONBOARDING_TRIAL_DAYS}-day`;
