'use client';
import { useCallback, useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { api } from '../../../lib/api';
import { useCurrency } from '../../../lib/useCurrency';
import { useToast } from '../../../lib/toast';

const BarChart = dynamic(() => import('recharts').then(mod => mod.BarChart), { ssr: false, loading: () => <div className="h-56 bg-gray-100 rounded-lg animate-pulse" /> });
const Bar = dynamic(() => import('recharts').then(mod => mod.Bar), { ssr: false });
const XAxis = dynamic(() => import('recharts').then(mod => mod.XAxis), { ssr: false });
const YAxis = dynamic(() => import('recharts').then(mod => mod.YAxis), { ssr: false });
const CartesianGrid = dynamic(() => import('recharts').then(mod => mod.CartesianGrid), { ssr: false });
const Tooltip = dynamic(() => import('recharts').then(mod => mod.Tooltip), { ssr: false });
const ResponsiveContainer = dynamic(() => import('recharts').then(mod => mod.ResponsiveContainer), { ssr: false });
const Legend = dynamic(() => import('recharts').then(mod => mod.Legend), { ssr: false });

import { PageHeader } from '../../../components/dashboard/PageHeader';

interface MonthlyPoint {
  month: string;    // "2025-12"
  income: number;
  expenses: number;
  net: number;
}

interface PeriodSummary {
  period: string;
  totalIncome: number;
  totalExpenses: number;
  netIncome: number;
  expensesByCategory: Record<string, number>;
  incomeByCategory: Record<string, number>;
  transactionCount: number;
}

const MONTHS_BACK = [1, 3, 6, 12];
const PERIOD_OPTIONS = [
  { value: 'month', label: 'This Month' },
  { value: 'year',  label: 'This Year' },
];

const CAT_ICONS: Record<string, string> = {
  food: '🍽️', transportation: '🚗', shopping: '🛒', utilities: '💡',
  housing: '🏠', healthcare: '🏥', education: '📚', entertainment: '🎬',
  subscription: '📱', charity: '🤲', income: '💰', investment: '📈',
  transfer: '💸', interest: '⚠️', other: '📋',
};

function fmtMonth(m: string) {
  const [y, mo] = m.split('-');
  const d = new Date(parseInt(y), parseInt(mo) - 1, 1);
  return d.toLocaleDateString(undefined, { month: 'short', year: '2-digit' });
}

// Cap runaway percentages (e.g. 14593.7% when prior month had ~$1 of expenses).
// Used in both the on-screen UI and the exported text so the copied summary
// doesn't produce "Expenses up 14593.7% vs prior month" which is bad UX.
function capPctValue(pct: string): string {
  const n = parseFloat(pct);
  if (Number.isNaN(n)) return pct;
  if (n > 999) return '>999';
  if (n < -999) return '<-999';
  return pct;
}

function generateText(summary: PeriodSummary, months: MonthlyPoint[], period: string, fmt: (n: number) => string): string {
  const net    = summary.netIncome;
  const rateRaw = summary.totalIncome > 0 ? (net / summary.totalIncome * 100).toFixed(1) : '0';
  const rate = capPctValue(rateRaw);
  const topCat = Object.entries(summary.expensesByCategory).sort((a, b) => b[1] - a[1])[0];
  const label  = period === 'month' ? 'this month' : 'this year';

  let text = `📊 Financial Summary — ${period === 'month' ? 'This Month' : 'This Year'}\n\n`;
  text += `Total Income:    ${fmt(summary.totalIncome)}\n`;
  text += `Total Expenses:  ${fmt(summary.totalExpenses)}\n`;
  text += `Net Income:      ${fmt(net)}\n`;
  text += `Savings Rate:    ${rate}%\n`;
  text += `Transactions:    ${summary.transactionCount}\n\n`;

  if (topCat) {
    text += `Top spending category ${label}: ${topCat[0].replace(/_/g, ' ')} (${fmt(topCat[1])})\n\n`;
  }

  if (months.length >= 2) {
    const last  = months[months.length - 1];
    const prev  = months[months.length - 2];
    const chg   = last.expenses - prev.expenses;
    const chgPct = prev.expenses > 0 ? (chg / prev.expenses * 100).toFixed(1) : '0';
    const capped = capPctValue(chgPct);
    // Strip leading '<'/'>' markers so the formatted string reads naturally
    // after Math.abs-style presentation.
    const display = capped.replace(/^[<>-]/, '');
    text += `Month-over-Month: Expenses ${chg >= 0 ? 'up' : 'down'} ${display}% vs prior month\n\n`;
  }

  text += `Generated by Barakah — ${new Date().toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}`;
  return text;
}

export default function SummaryPage() {
  const { fmt, symbol } = useCurrency();
  const [period, setPeriod]         = useState<'month' | 'year'>('month');
  const [months, setMonths]         = useState(6);
  const [summary, setSummary]       = useState<PeriodSummary | null>(null);
  const [monthly, setMonthly]       = useState<MonthlyPoint[]>([]);
  const [loading, setLoading]       = useState(true);
  const [copied, setCopied]         = useState(false);
  const { toast } = useToast();

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const results = await Promise.allSettled([
        api.getTransactionSummary(period),
        api.getMonthlySummary(months),
      ]);
      const s = results[0].status === 'fulfilled' ? results[0].value : null;
      const m = results[1].status === 'fulfilled' ? results[1].value : null;
      setSummary(s);
      setMonthly(m?.months || []);
    } catch {
      toast('Failed to load summary data', 'error');
    } finally {
      setLoading(false);
    }
  }, [months, period, toast]);

  useEffect(() => { void load(); }, [load]);

  const handleCopy = () => {
    if (!summary) return;
    const text = generateText(summary, monthly, period, fmt);
    navigator.clipboard.writeText(text)
      .then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); })
      .catch(() => toast('Could not copy text', 'error'));
  };

  if (loading) return (
    <div className="flex justify-center py-20">
      <div className="animate-spin w-8 h-8 border-4 border-[#1B5E20] border-t-transparent rounded-full" />
    </div>
  );

  if (!summary) return (
    <div className="text-center py-16 text-gray-400">
      <p className="text-4xl mb-3">📊</p>
      <p>No data available yet. Import some transactions to get started.</p>
    </div>
  );

  // Cap extreme percentages so elderly / new users aren't alarmed by values
  // like "-2783%" or "140955%". Anything beyond ±999% is shown as ">999%".
  // See capPctValue() at module scope — shared with generateText() so the
  // exported text summary has the same capping as the on-screen UI.
  const savingsRateRaw = summary.totalIncome > 0
    ? ((summary.netIncome / summary.totalIncome) * 100).toFixed(1)
    : '0.0';
  const savingsRate = capPctValue(savingsRateRaw);

  const expenseEntries = Object.entries(summary.expensesByCategory)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);

  const momChange = monthly.length >= 2
    ? monthly[monthly.length - 1].expenses - monthly[monthly.length - 2].expenses
    : 0;
  const momPctRaw = monthly.length >= 2 && monthly[monthly.length - 2].expenses > 0
    ? (momChange / monthly[monthly.length - 2].expenses * 100).toFixed(1)
    : '0.0';
  const momPct = capPctValue(momPctRaw);

  const chartData = monthly.map(d => ({ label: fmtMonth(d.month), income: d.income, expenses: d.expenses, net: d.net }));

  return (
    <div className="max-w-2xl mx-auto">
      {/* Header */}
      <PageHeader
        title="Financial Summary"
        subtitle="Overview of your income and spending"
        actions={
          <button
            onClick={handleCopy}
            className="bg-[#1B5E20] text-white px-4 py-2 rounded-lg text-sm hover:bg-[#2E7D32] font-medium transition"
          >
            {copied ? '✓ Copied' : '📋 Copy Summary'}
          </button>
        }
      />

      {/* Controls */}
      <div className="flex gap-3 mb-6 flex-wrap">
        <div className="flex gap-2">
          {PERIOD_OPTIONS.map(p => (
            <button
              key={p.value}
              onClick={() => setPeriod(p.value as 'month' | 'year')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
                period === p.value ? 'bg-[#1B5E20] text-white' : 'bg-white text-gray-600 hover:bg-gray-100'
              }`}
            >
              {p.label}
            </button>
          ))}
        </div>
        <div className="flex gap-2">
          {MONTHS_BACK.map(m => (
            <button
              key={m}
              onClick={() => setMonths(m)}
              className={`px-3 py-2 rounded-lg text-sm font-medium transition ${
                months === m ? 'bg-[#1B5E20] text-white' : 'bg-white text-gray-600 hover:bg-gray-100'
              }`}
            >
              {m}m
            </button>
          ))}
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 gap-3 mb-6">
        <div className="bg-gradient-to-br from-[#1B5E20] to-green-500 rounded-xl p-5 text-white">
          <p className="text-green-200 text-xs uppercase tracking-wide">Total Income</p>
          <p className="text-2xl font-bold mt-1">{fmt(summary.totalIncome)}</p>
        </div>
        <div className="bg-gradient-to-br from-red-600 to-red-400 rounded-xl p-5 text-white">
          <p className="text-red-200 text-xs uppercase tracking-wide">Total Expenses</p>
          <p className="text-2xl font-bold mt-1">{fmt(summary.totalExpenses)}</p>
        </div>
        <div className={`rounded-xl p-5 text-white ${summary.netIncome >= 0 ? 'bg-gradient-to-br from-teal-600 to-cyan-500' : 'bg-gradient-to-br from-orange-600 to-amber-500'}`}>
          <p className="opacity-80 text-xs uppercase tracking-wide">Net Income</p>
          <p className="text-2xl font-bold mt-1">{fmt(summary.netIncome)}</p>
        </div>
        <div className="bg-gradient-to-br from-purple-600 to-indigo-500 rounded-xl p-5 text-white">
          <p className="text-purple-200 text-xs uppercase tracking-wide">Savings Rate</p>
          <p className="text-2xl font-bold mt-1">{savingsRate}%</p>
          <p className="text-purple-200 text-xs mt-0.5">{summary.transactionCount} txns</p>
        </div>
      </div>

      {/* MoM badge */}
      {monthly.length >= 2 && (
        <div className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium mb-5 ${
          momChange === 0 ? 'bg-gray-50 text-gray-700' : momChange < 0 ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'
        }`}>
          {momChange === 0
            ? <>→ Spending unchanged vs last month</>
            : <>{momChange < 0 ? '↓ Spending down' : '↑ Spending up'} {momPct.replace(/^[<>-]/, '')}% vs last month</>}
        </div>
      )}

      {/* Trend chart */}
      {chartData.length > 0 && (
        <div className="bg-white rounded-2xl p-5 shadow-sm mb-5">
          <h2 className="font-semibold text-[#1B5E20] mb-4">Income vs Expenses — Last {months} Months</h2>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={chartData} margin={{ top: 0, right: 0, left: -10, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="label" tick={{ fontSize: 10 }} />
              <YAxis tick={{ fontSize: 10 }} tickFormatter={v => symbol + (v >= 1000 ? (v / 1000).toFixed(0) + 'k' : v)} />
              <Tooltip formatter={(value) => fmt(Number(value))} />
              <Legend wrapperStyle={{ fontSize: 12 }} />
              <Bar dataKey="income"   name="Income"   fill="#1B5E20" radius={[4, 4, 0, 0]} />
              <Bar dataKey="expenses" name="Expenses" fill="#EF4444" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Top spending categories */}
      <div className="bg-white rounded-2xl p-5 shadow-sm mb-5">
        <h2 className="font-semibold text-[#1B5E20] mb-4">Top Spending Categories</h2>
        {expenseEntries.length === 0 ? (
          <p className="text-gray-400 text-sm text-center py-4">No expense data for this period</p>
        ) : (
          <div className="space-y-3">
            {expenseEntries.map(([cat, amt], i) => {
              const pct = summary.totalExpenses > 0 ? (amt / summary.totalExpenses * 100) : 0;
              return (
                <div key={cat}>
                  <div className="flex justify-between items-center mb-1">
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{CAT_ICONS[cat] ?? '📋'}</span>
                      <span className="text-sm font-medium text-gray-700 capitalize">{cat.replace(/_/g, ' ')}</span>
                    </div>
                    <div className="text-right">
                      <span className="text-sm font-bold text-gray-800">{fmt(amt)}</span>
                      <span className="text-xs text-gray-400 ml-1">{pct.toFixed(1)}%</span>
                    </div>
                  </div>
                  <div className="w-full bg-gray-100 rounded-full h-1.5">
                    <div
                      className="h-1.5 rounded-full"
                      style={{ width: `${pct}%`, backgroundColor: i === 0 ? '#EF4444' : i === 1 ? '#F59E0B' : '#6B7280' }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Shareable text preview */}
      <div className="bg-white rounded-2xl p-5 shadow-sm mb-5">
        <div className="flex justify-between items-center mb-3">
          <h2 className="font-semibold text-[#1B5E20]">Text Summary</h2>
          <button
            onClick={handleCopy}
            className="text-sm text-[#1B5E20] hover:underline font-medium"
          >
            {copied ? '✓ Copied!' : 'Copy'}
          </button>
        </div>
        <pre className="bg-gray-50 rounded-xl p-4 text-xs text-gray-700 whitespace-pre-wrap font-mono leading-relaxed">
          {generateText(summary, monthly, period, fmt)}
        </pre>
      </div>
    </div>
  );
}
